import { db } from "@workspace/db";
import { productsTable, categoriesTable, cartItemsTable, cartSessionsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("Seeding AxiomCraft database...");

  await db.delete(cartItemsTable);
  await db.delete(cartSessionsTable);
  await db.delete(productsTable);
  await db.delete(categoriesTable);

  await db.insert(categoriesTable).values([
    { name: "Motherboards", slug: "motherboards", description: "High-performance ATX and mATX motherboards with cutting-edge PCIe 5.0 and DDR5 support" },
    { name: "Graphics Cards", slug: "gpus", description: "Next-gen GPUs built for 4K gaming, AI workloads, and professional rendering" },
    { name: "Memory", slug: "memory", description: "Ultra-fast DDR5 RAM for extreme overclocking and workstation performance" },
    { name: "Storage", slug: "storage", description: "Blazing-fast NVMe PCIe 5.0 SSDs and enterprise-grade HDDs" },
    { name: "Power Supplies", slug: "psus", description: "80+ Titanium rated PSUs engineered for maximum efficiency and stability" },
    { name: "Processors", slug: "cpus", description: "Elite desktop CPUs for gaming, content creation, and compute-intensive workloads" },
  ]);

  await db.insert(productsTable).values([
    {
      name: "AXIOM X870E APEX",
      slug: "axiom-x870e-apex",
      category: "Motherboards",
      categorySlug: "motherboards",
      shortDescription: "AM5 flagship motherboard with dual PCIe 5.0 x16 slots and 20+2 power stages",
      description: "The AXIOM X870E APEX redefines premium desktop computing. Built on the AMD X870E chipset with Socket AM5, this board delivers uncompromising performance for Ryzen 9000 series processors. Features dual PCIe 5.0 x16 slots, quad M.2 slots, and a robust 20+2+2 power delivery system rated at 105A per phase.",
      basePrice: "899.99",
      salePrice: null,
      stock: 12,
      sku: "AX-MB-X870E-APEX",
      imageUrl: "https://picsum.photos/seed/axiom-x870e-apex/800/600",
      badge: "Flagship",
      specs: [
        { name: "Socket", value: "AM5" },
        { name: "Chipset", value: "AMD X870E" },
        { name: "Form Factor", value: "ATX" },
        { name: "Memory Slots", value: "4 x DDR5" },
        { name: "Max Memory", value: "256GB DDR5-8000+" },
        { name: "PCIe Slots", value: "2x PCIe 5.0 x16, 1x PCIe 4.0 x16" },
        { name: "M.2 Slots", value: "4 x M.2 PCIe 5.0/4.0" },
        { name: "USB", value: "USB 3.2 Gen 2x2, Thunderbolt 4" },
        { name: "Network", value: "10GbE + 2.5GbE + WiFi 7" },
        { name: "Power Phases", value: "20+2+2 (105A per phase)" },
      ],
      variants: [
        { id: 1, name: "Standard", sku: "AX-MB-X870E-APEX-STD", priceModifier: 0, stock: 8, attributes: { bundle: "None" } },
        { id: 2, name: "With WiFi Upgrade Kit", sku: "AX-MB-X870E-APEX-WIFI", priceModifier: 49.99, stock: 4, attributes: { bundle: "WiFi 7 Upgrade" } },
      ],
      tags: ["am5", "x870e", "ddr5", "pcie5", "flagship", "overclocking"],
    },
    {
      name: "AXIOM Z890 STORM",
      slug: "axiom-z890-storm",
      category: "Motherboards",
      categorySlug: "motherboards",
      shortDescription: "Intel LGA1851 motherboard with AI-powered overclocking and PCIe 5.0",
      description: "Engineered for Intel Core Ultra 200 processors, the AXIOM Z890 STORM delivers AI-assisted overclocking with 18+1+2 power stages. Dual Thunderbolt 4 ports, quad PCIe 5.0 M.2 slots, and onboard BIOS flashback capability.",
      basePrice: "749.99",
      salePrice: "699.99",
      stock: 18,
      sku: "AX-MB-Z890-STORM",
      imageUrl: "https://picsum.photos/seed/axiom-z890-storm/800/600",
      badge: "On Sale",
      specs: [
        { name: "Socket", value: "LGA1851" },
        { name: "Chipset", value: "Intel Z890" },
        { name: "Form Factor", value: "ATX" },
        { name: "Memory Slots", value: "4 x DDR5" },
        { name: "Max Memory", value: "192GB DDR5-9600+" },
        { name: "PCIe Slots", value: "1x PCIe 5.0 x16, 2x PCIe 4.0 x4" },
        { name: "M.2 Slots", value: "4 x M.2 PCIe 5.0/4.0" },
        { name: "USB", value: "2x Thunderbolt 4, USB 3.2 Gen 2x2" },
        { name: "Network", value: "5GbE + 2.5GbE + WiFi 7" },
        { name: "Power Phases", value: "18+1+2 (90A per phase)" },
      ],
      variants: [
        { id: 1, name: "Standard", sku: "AX-MB-Z890-STD", priceModifier: 0, stock: 14, attributes: {} },
        { id: 2, name: "Bundled with 32GB DDR5", sku: "AX-MB-Z890-MEM", priceModifier: 159.99, stock: 4, attributes: { bundle: "32GB DDR5-6400" } },
      ],
      tags: ["lga1851", "z890", "intel", "ddr5", "pcie5", "overclocking"],
    },
    {
      name: "AXIOM X670E PRO",
      slug: "axiom-x670e-pro",
      category: "Motherboards",
      categorySlug: "motherboards",
      shortDescription: "Mid-range AM5 board with PCIe 5.0 x16 and DDR5-6000 support",
      description: "The sweet spot of the AxiomCraft motherboard lineup. Delivers X670E features at a more accessible price point without compromising on connectivity or build quality.",
      basePrice: "499.99",
      salePrice: null,
      stock: 0,
      sku: "AX-MB-X670E-PRO",
      imageUrl: "https://picsum.photos/seed/axiom-x670e-pro/800/600",
      badge: "Out of Stock",
      specs: [
        { name: "Socket", value: "AM5" },
        { name: "Chipset", value: "AMD X670E" },
        { name: "Form Factor", value: "ATX" },
        { name: "Memory Slots", value: "4 x DDR5" },
        { name: "Max Memory", value: "128GB DDR5-6000+" },
        { name: "PCIe Slots", value: "1x PCIe 5.0 x16, 1x PCIe 4.0 x16" },
        { name: "M.2 Slots", value: "3 x M.2 PCIe 5.0/4.0" },
        { name: "Network", value: "2.5GbE + WiFi 6E" },
        { name: "Power Phases", value: "14+2 (80A per phase)" },
      ],
      variants: [],
      tags: ["am5", "x670e", "ddr5", "mid-range"],
    },
    {
      name: "AXIOM RTX 5090 TITAN X",
      slug: "axiom-rtx-5090-titan-x",
      category: "Graphics Cards",
      categorySlug: "gpus",
      shortDescription: "NVIDIA RTX 5090 with 32GB GDDR7 and triple-fan cooling",
      description: "The absolute pinnacle of GPU performance. The AXIOM RTX 5090 TITAN X features NVIDIA's Blackwell architecture with 24,576 CUDA cores, 32GB of ultra-fast GDDR7 memory, and our proprietary FrostBlade III triple-fan cooling system maintaining sub-60°C under full load.",
      basePrice: "2499.99",
      salePrice: null,
      stock: 3,
      sku: "AX-GPU-RTX5090-TX",
      imageUrl: "https://picsum.photos/seed/axiom-rtx-5090-titan-x/800/600",
      badge: "Limited Stock",
      specs: [
        { name: "GPU Chip", value: "NVIDIA RTX 5090 (Blackwell GB202)" },
        { name: "CUDA Cores", value: "24,576" },
        { name: "VRAM", value: "32GB GDDR7" },
        { name: "Memory Bus", value: "512-bit" },
        { name: "Memory Bandwidth", value: "1,792 GB/s" },
        { name: "Base Clock", value: "2,017 MHz" },
        { name: "Boost Clock", value: "2,900 MHz" },
        { name: "TDP", value: "575W" },
        { name: "Power Connector", value: "2x 16-pin 12VHPWR" },
        { name: "Display Outputs", value: "3x DisplayPort 2.1, 1x HDMI 2.1" },
        { name: "Form Factor", value: "Triple-slot, 370mm" },
      ],
      variants: [],
      tags: ["rtx5090", "nvidia", "blackwell", "4k", "8k", "flagship"],
    },
    {
      name: "AXIOM RTX 5080 PHANTOM",
      slug: "axiom-rtx-5080-phantom",
      category: "Graphics Cards",
      categorySlug: "gpus",
      shortDescription: "RTX 5080 with 16GB GDDR7 — the 4K performance king",
      description: "Supreme 4K gaming and AI acceleration at a compelling price-to-performance ratio. The AXIOM RTX 5080 PHANTOM delivers flagship-tier rendering with DLSS 4 Multi Frame Generation support.",
      basePrice: "1199.99",
      salePrice: "1099.99",
      stock: 9,
      sku: "AX-GPU-RTX5080-PH",
      imageUrl: "https://picsum.photos/seed/axiom-rtx-5080-phantom/800/600",
      badge: "Best Value",
      specs: [
        { name: "GPU Chip", value: "NVIDIA RTX 5080 (Blackwell GB203)" },
        { name: "CUDA Cores", value: "10,752" },
        { name: "VRAM", value: "16GB GDDR7" },
        { name: "Memory Bus", value: "256-bit" },
        { name: "Memory Bandwidth", value: "896 GB/s" },
        { name: "Boost Clock", value: "2,950 MHz" },
        { name: "TDP", value: "360W" },
        { name: "Form Factor", value: "Triple-slot, 340mm" },
      ],
      variants: [],
      tags: ["rtx5080", "nvidia", "4k", "gaming", "ai"],
    },
    {
      name: "AXIOM RX 9900 XTX VEGA",
      slug: "axiom-rx-9900-xtx-vega",
      category: "Graphics Cards",
      categorySlug: "gpus",
      shortDescription: "AMD RX 9900 XTX with 24GB GDDR6 and liquid-assisted cooling",
      description: "AMD's RDNA 4 flagship GPU in AxiomCraft's reference-grade cooling solution. Superior rasterization performance with FSR 4 AI upscaling and AV1 hardware encode/decode.",
      basePrice: "999.99",
      salePrice: null,
      stock: 15,
      sku: "AX-GPU-RX9900XTX-VG",
      imageUrl: "https://picsum.photos/seed/axiom-rx-9900-xtx-vega/800/600",
      badge: null,
      specs: [
        { name: "GPU Chip", value: "AMD RX 9900 XTX (RDNA 4)" },
        { name: "Compute Units", value: "64 (RDNA 4)" },
        { name: "VRAM", value: "24GB GDDR6" },
        { name: "Memory Bus", value: "384-bit" },
        { name: "Memory Bandwidth", value: "960 GB/s" },
        { name: "Game Clock", value: "2,700 MHz" },
        { name: "TDP", value: "330W" },
        { name: "Form Factor", value: "Triple-slot, 320mm" },
      ],
      variants: [],
      tags: ["rx9900xtx", "amd", "rdna4", "4k", "gaming"],
    },
    {
      name: "AXIOM DDR5-8000 HYPERION 64GB Kit",
      slug: "axiom-ddr5-8000-hyperion-64gb",
      category: "Memory",
      categorySlug: "memory",
      shortDescription: "2x32GB DDR5-8000 CL38 with RGB and XMP 3.0 support",
      description: "Engineered for extreme overclocking on AMD X870E and Intel Z890 platforms. Each module is individually binned and tested at 8000 MT/s with tight CL38 timings. Includes XMP 3.0 and EXPO profiles.",
      basePrice: "399.99",
      salePrice: null,
      stock: 25,
      sku: "AX-MEM-DDR5-8000-64G",
      imageUrl: "https://picsum.photos/seed/axiom-ddr5-8000-hyperion-64gb/800/600",
      badge: "Top Pick",
      specs: [
        { name: "Capacity", value: "64GB (2x32GB)" },
        { name: "Type", value: "DDR5" },
        { name: "Speed", value: "8000 MT/s" },
        { name: "Latency", value: "CL38-48-48-96" },
        { name: "Voltage", value: "1.45V" },
        { name: "Profile", value: "XMP 3.0 / EXPO" },
        { name: "RGB", value: "Addressable RGB (ARGB)" },
        { name: "Heat Spreader", value: "Aluminum alloy" },
        { name: "Form Factor", value: "DIMM" },
        { name: "ECC", value: "Non-ECC" },
      ],
      variants: [
        { id: 1, name: "64GB (2x32GB)", sku: "AX-MEM-DDR5-8000-64G", priceModifier: 0, stock: 18, attributes: { capacity: "64GB" } },
        { id: 2, name: "32GB (2x16GB)", sku: "AX-MEM-DDR5-8000-32G", priceModifier: -120, stock: 7, attributes: { capacity: "32GB" } },
        { id: 3, name: "128GB (4x32GB)", sku: "AX-MEM-DDR5-8000-128G", priceModifier: 399.99, stock: 4, attributes: { capacity: "128GB" } },
      ],
      tags: ["ddr5", "ddr5-8000", "overclocking", "rgb", "xmp3"],
    },
    {
      name: "AXIOM DDR5-6400 NOVA 32GB Kit",
      slug: "axiom-ddr5-6400-nova-32gb",
      category: "Memory",
      categorySlug: "memory",
      shortDescription: "2x16GB DDR5-6400 CL32 — the performance baseline redefined",
      description: "The NOVA series delivers exceptional performance at a more accessible price point. Factory-tested at DDR5-6400 with CL32 timings, perfect for Ryzen 7000/9000 and Intel Core Ultra builds.",
      basePrice: "189.99",
      salePrice: "159.99",
      stock: 42,
      sku: "AX-MEM-DDR5-6400-32G",
      imageUrl: "https://picsum.photos/seed/axiom-ddr5-6400-nova-32gb/800/600",
      badge: "On Sale",
      specs: [
        { name: "Capacity", value: "32GB (2x16GB)" },
        { name: "Type", value: "DDR5" },
        { name: "Speed", value: "6400 MT/s" },
        { name: "Latency", value: "CL32-39-39-102" },
        { name: "Voltage", value: "1.35V" },
        { name: "Profile", value: "XMP 3.0 / EXPO" },
        { name: "RGB", value: "None" },
        { name: "Form Factor", value: "DIMM" },
      ],
      variants: [
        { id: 1, name: "32GB (2x16GB)", sku: "AX-MEM-DDR5-6400-32G", priceModifier: 0, stock: 30, attributes: { capacity: "32GB" } },
        { id: 2, name: "64GB (2x32GB)", sku: "AX-MEM-DDR5-6400-64G", priceModifier: 159.99, stock: 12, attributes: { capacity: "64GB" } },
      ],
      tags: ["ddr5", "ddr5-6400", "value", "amd", "intel"],
    },
    {
      name: "AXIOM APEX NVMe 4TB PCIe 5.0",
      slug: "axiom-apex-nvme-4tb-pcie5",
      category: "Storage",
      categorySlug: "storage",
      shortDescription: "14,500 MB/s sequential read — the world's fastest consumer SSD",
      description: "Built on Phison E26 controller with 232-layer QLC NAND, the AXIOM APEX NVMe delivers unprecedented sequential speeds in a standard M.2 2280 form factor. Includes copper heatspreader and thermal throttle protection.",
      basePrice: "449.99",
      salePrice: null,
      stock: 20,
      sku: "AX-SSD-APEX-4TB-5G",
      imageUrl: "https://picsum.photos/seed/axiom-apex-nvme-4tb-pcie5/800/600",
      badge: "World's Fastest",
      specs: [
        { name: "Capacity", value: "4TB" },
        { name: "Interface", value: "M.2 PCIe 5.0 x4 NVMe 2.0" },
        { name: "Form Factor", value: "M.2 2280" },
        { name: "Sequential Read", value: "14,500 MB/s" },
        { name: "Sequential Write", value: "12,700 MB/s" },
        { name: "Random Read IOPS", value: "1,500,000 IOPS" },
        { name: "Random Write IOPS", value: "1,400,000 IOPS" },
        { name: "NAND Type", value: "232-Layer QLC NAND" },
        { name: "Controller", value: "Phison E26" },
        { name: "DRAM Cache", value: "4GB LPDDR4" },
        { name: "Endurance", value: "1,500 TBW" },
        { name: "Warranty", value: "5 Years" },
      ],
      variants: [
        { id: 1, name: "2TB", sku: "AX-SSD-APEX-2TB-5G", priceModifier: -150, stock: 14, attributes: { capacity: "2TB" } },
        { id: 2, name: "4TB", sku: "AX-SSD-APEX-4TB-5G", priceModifier: 0, stock: 6, attributes: { capacity: "4TB" } },
      ],
      tags: ["nvme", "pcie5", "m.2", "ssd", "high-performance"],
    },
    {
      name: "AXIOM VECTOR NVMe 2TB PCIe 4.0",
      slug: "axiom-vector-nvme-2tb-pcie4",
      category: "Storage",
      categorySlug: "storage",
      shortDescription: "7,400 MB/s sequential — the everyday performance champion",
      description: "The VECTOR series NVMe delivers class-leading PCIe 4.0 performance for mainstream builds. Perfect for OS drive, game storage, and creative workstation use cases.",
      basePrice: "169.99",
      salePrice: "149.99",
      stock: 55,
      sku: "AX-SSD-VEC-2TB-4G",
      imageUrl: "https://picsum.photos/seed/axiom-vector-nvme-2tb-pcie4/800/600",
      badge: "Best Seller",
      specs: [
        { name: "Capacity", value: "2TB" },
        { name: "Interface", value: "M.2 PCIe 4.0 x4 NVMe 1.4" },
        { name: "Form Factor", value: "M.2 2280" },
        { name: "Sequential Read", value: "7,400 MB/s" },
        { name: "Sequential Write", value: "6,900 MB/s" },
        { name: "NAND Type", value: "176-Layer TLC NAND" },
        { name: "Endurance", value: "1,200 TBW" },
        { name: "Warranty", value: "5 Years" },
      ],
      variants: [
        { id: 1, name: "1TB", sku: "AX-SSD-VEC-1TB-4G", priceModifier: -70, stock: 25, attributes: { capacity: "1TB" } },
        { id: 2, name: "2TB", sku: "AX-SSD-VEC-2TB-4G", priceModifier: 0, stock: 20, attributes: { capacity: "2TB" } },
        { id: 3, name: "4TB", sku: "AX-SSD-VEC-4TB-4G", priceModifier: 130, stock: 10, attributes: { capacity: "4TB" } },
      ],
      tags: ["nvme", "pcie4", "m.2", "ssd", "value"],
    },
    {
      name: "AXIOM TITAN HDD 20TB Enterprise",
      slug: "axiom-titan-hdd-20tb",
      category: "Storage",
      categorySlug: "storage",
      shortDescription: "20TB CMR HDD with 7200RPM and 512MB cache",
      description: "Massive storage capacity with enterprise-grade reliability. The AXIOM TITAN 20TB features conventional magnetic recording for maximum sequential throughput and long-term data integrity for workstations and NAS systems.",
      basePrice: "329.99",
      salePrice: null,
      stock: 22,
      sku: "AX-HDD-TITAN-20TB",
      imageUrl: "https://picsum.photos/seed/axiom-titan-hdd-20tb/800/600",
      badge: null,
      specs: [
        { name: "Capacity", value: "20TB" },
        { name: "Interface", value: "SATA 6Gb/s" },
        { name: "RPM", value: "7,200 RPM" },
        { name: "Cache", value: "512MB" },
        { name: "Recording Method", value: "CMR (Conventional Magnetic)" },
        { name: "Sequential Read", value: "285 MB/s" },
        { name: "MTBF", value: "2,500,000 hours" },
        { name: "Warranty", value: "5 Years" },
      ],
      variants: [
        { id: 1, name: "16TB", sku: "AX-HDD-TITAN-16TB", priceModifier: -80, stock: 12, attributes: { capacity: "16TB" } },
        { id: 2, name: "20TB", sku: "AX-HDD-TITAN-20TB", priceModifier: 0, stock: 10, attributes: { capacity: "20TB" } },
      ],
      tags: ["hdd", "sata", "storage", "nas", "enterprise"],
    },
    {
      name: "AXIOM FORGE PSU 1600W Titanium",
      slug: "axiom-forge-psu-1600w-titanium",
      category: "Power Supplies",
      categorySlug: "psus",
      shortDescription: "80+ Titanium, fully modular, 1600W — engineered for RTX 5090 builds",
      description: "The AXIOM FORGE 1600W is built for the most demanding PC configurations. 80+ Titanium efficiency (up to 96%), fully modular cable management, and premium Japanese capacitors rated for 100,000 hours of operation.",
      basePrice: "449.99",
      salePrice: null,
      stock: 8,
      sku: "AX-PSU-FORGE-1600T",
      imageUrl: "https://picsum.photos/seed/axiom-forge-psu-1600w-titanium/800/600",
      badge: "Premium",
      specs: [
        { name: "Wattage", value: "1,600W" },
        { name: "Efficiency", value: "80+ Titanium (96% @ 50% load)" },
        { name: "Modular", value: "Fully Modular" },
        { name: "Fan Size", value: "135mm FDB bearing" },
        { name: "ATX Version", value: "ATX 3.0" },
        { name: "PCIe Cables", value: "4x 16-pin 12VHPWR, 8x PCIe 8-pin" },
        { name: "Protection", value: "OVP, UVP, OCP, SCP, OTP, OPP" },
        { name: "Capacitors", value: "100% Japanese (105°C rated)" },
        { name: "MTBF", value: "100,000 hours" },
        { name: "Warranty", value: "10 Years" },
        { name: "Dimensions", value: "160mm x 150mm x 86mm" },
      ],
      variants: [],
      tags: ["psu", "titanium", "1600w", "modular", "atx3"],
    },
    {
      name: "AXIOM FORGE PSU 1000W Gold",
      slug: "axiom-forge-psu-1000w-gold",
      category: "Power Supplies",
      categorySlug: "psus",
      shortDescription: "1000W 80+ Gold fully modular — the mainstream powerhouse",
      description: "Reliable, efficient, and whisper-quiet. The FORGE 1000W Gold is the go-to PSU for RTX 5080, RX 9900 XTX, and multi-drive builds. 80+ Gold certified with semi-fanless mode below 30% load.",
      basePrice: "199.99",
      salePrice: "179.99",
      stock: 30,
      sku: "AX-PSU-FORGE-1000G",
      imageUrl: "https://picsum.photos/seed/axiom-forge-psu-1000w-gold/800/600",
      badge: "On Sale",
      specs: [
        { name: "Wattage", value: "1,000W" },
        { name: "Efficiency", value: "80+ Gold (92% @ 50% load)" },
        { name: "Modular", value: "Fully Modular" },
        { name: "Fan Size", value: "120mm FDB bearing" },
        { name: "ATX Version", value: "ATX 3.0" },
        { name: "PCIe Cables", value: "2x 16-pin 12VHPWR, 4x PCIe 8-pin" },
        { name: "Protection", value: "OVP, UVP, OCP, SCP, OTP" },
        { name: "Warranty", value: "7 Years" },
      ],
      variants: [
        { id: 1, name: "750W Gold", sku: "AX-PSU-FORGE-750G", priceModifier: -40, stock: 20, attributes: { wattage: "750W" } },
        { id: 2, name: "1000W Gold", sku: "AX-PSU-FORGE-1000G", priceModifier: 0, stock: 10, attributes: { wattage: "1000W" } },
      ],
      tags: ["psu", "gold", "1000w", "modular"],
    },
    {
      name: "AXIOM RYZEN 9 9950X3D",
      slug: "axiom-ryzen-9-9950x3d",
      category: "Processors",
      categorySlug: "cpus",
      shortDescription: "16 cores, 32 threads, 3D V-Cache — ultimate gaming + creation CPU",
      description: "The pinnacle of consumer CPU performance. AMD Ryzen 9 9950X3D combines 16 Zen 5 cores with 128MB of 3D V-Cache, delivering unmatched single-threaded gaming performance alongside ferocious multi-threaded creative workloads.",
      basePrice: "699.99",
      salePrice: null,
      stock: 11,
      sku: "AX-CPU-R9-9950X3D",
      imageUrl: "https://picsum.photos/seed/axiom-ryzen-9-9950x3d/800/600",
      badge: "New",
      specs: [
        { name: "Socket", value: "AM5" },
        { name: "Cores / Threads", value: "16C / 32T" },
        { name: "Base Clock", value: "4.3 GHz" },
        { name: "Boost Clock", value: "5.7 GHz" },
        { name: "Total Cache", value: "144MB (16MB L2 + 128MB 3D V-Cache)" },
        { name: "TDP", value: "170W cTDP" },
        { name: "Architecture", value: "Zen 5" },
        { name: "Process Node", value: "TSMC N4P + N6" },
        { name: "Memory Support", value: "DDR5-5200 (JEDEC) / DDR5-8000+ (OC)" },
        { name: "PCIe Lanes", value: "28x PCIe 5.0" },
      ],
      variants: [],
      tags: ["ryzen9", "am5", "zen5", "3dvcache", "gaming", "flagship"],
    },
    {
      name: "AXIOM RYZEN 7 9700X",
      slug: "axiom-ryzen-7-9700x",
      category: "Processors",
      categorySlug: "cpus",
      shortDescription: "8 cores, Zen 5, 65W TDP — efficiency meets performance",
      description: "Best-in-class performance-per-watt on the AM5 platform. The Ryzen 7 9700X runs cool and quiet at 65W while delivering gaming performance that rivals higher-wattage chips.",
      basePrice: "359.99",
      salePrice: "329.99",
      stock: 28,
      sku: "AX-CPU-R7-9700X",
      imageUrl: "https://picsum.photos/seed/axiom-ryzen-7-9700x/800/600",
      badge: "Best Value",
      specs: [
        { name: "Socket", value: "AM5" },
        { name: "Cores / Threads", value: "8C / 16T" },
        { name: "Base Clock", value: "3.8 GHz" },
        { name: "Boost Clock", value: "5.5 GHz" },
        { name: "Total Cache", value: "40MB" },
        { name: "TDP", value: "65W" },
        { name: "Architecture", value: "Zen 5" },
        { name: "Memory Support", value: "DDR5-5200 (JEDEC) / DDR5-7200+ (OC)" },
      ],
      variants: [],
      tags: ["ryzen7", "am5", "zen5", "efficiency", "value"],
    },
    {
      name: "AXIOM CORE ULTRA 9 285K",
      slug: "axiom-core-ultra-9-285k",
      category: "Processors",
      categorySlug: "cpus",
      shortDescription: "24 cores (8P+16E), Arrow Lake — Intel's performance flagship",
      description: "Intel Core Ultra 9 285K brings Arrow Lake's heterogeneous architecture to the desktop. 8 Performance cores paired with 16 Efficiency cores, optimized for AI-accelerated workloads and competitive gaming.",
      basePrice: "589.99",
      salePrice: null,
      stock: 16,
      sku: "AX-CPU-CU9-285K",
      imageUrl: "https://picsum.photos/seed/axiom-core-ultra-9-285k/800/600",
      badge: null,
      specs: [
        { name: "Socket", value: "LGA1851" },
        { name: "Cores / Threads", value: "24C (8P+16E) / 24T" },
        { name: "Base P-Core Clock", value: "3.7 GHz" },
        { name: "Boost P-Core Clock", value: "5.7 GHz" },
        { name: "Total Cache", value: "36MB L3 + 40MB L2" },
        { name: "TDP", value: "125W PBP / 250W MTP" },
        { name: "Architecture", value: "Arrow Lake (Intel 20A)" },
        { name: "Memory Support", value: "DDR5-6400 (native)" },
        { name: "PCIe Lanes", value: "24x PCIe 5.0 + 4x PCIe 4.0" },
        { name: "NPU", value: "Intel AI Boost NPU (48 TOPS)" },
      ],
      variants: [],
      tags: ["intel", "lga1851", "arrowlake", "flagship", "gaming"],
    },
    {
      name: "AXIOM VORTEX mATX AM5",
      slug: "axiom-vortex-matx-am5",
      category: "Motherboards",
      categorySlug: "motherboards",
      shortDescription: "Compact mATX X670 board for AM5 — small form factor, no compromises",
      description: "For builders who demand the best in a smaller footprint. The VORTEX mATX delivers dual PCIe 5.0 M.2 slots, USB 3.2 Gen 2x2, and 14+2 power stages in the mATX form factor.",
      basePrice: "329.99",
      salePrice: null,
      stock: 19,
      sku: "AX-MB-VORTEX-MATX",
      imageUrl: "https://picsum.photos/seed/axiom-vortex-matx-am5/800/600",
      badge: null,
      specs: [
        { name: "Socket", value: "AM5" },
        { name: "Chipset", value: "AMD X670" },
        { name: "Form Factor", value: "mATX" },
        { name: "Memory Slots", value: "4 x DDR5" },
        { name: "Max Memory", value: "128GB DDR5-6400+" },
        { name: "PCIe Slots", value: "1x PCIe 5.0 x16, 1x PCIe 3.0 x1" },
        { name: "M.2 Slots", value: "2 x M.2 PCIe 5.0/4.0" },
        { name: "Network", value: "2.5GbE + WiFi 6E" },
        { name: "Power Phases", value: "14+2 (70A per phase)" },
      ],
      variants: [],
      tags: ["am5", "x670", "matx", "compact"],
    },
    {
      name: "AXIOM FROST DDR5-7200 16GB Kit",
      slug: "axiom-frost-ddr5-7200-16gb",
      category: "Memory",
      categorySlug: "memory",
      shortDescription: "2x8GB DDR5-7200 CL34 — entry-level performance with flagship headroom",
      description: "The FROST series provides a stepping stone to DDR5 excellence. Factory-validated at 7200 MT/s with CL34 timings.",
      basePrice: "89.99",
      salePrice: "79.99",
      stock: 60,
      sku: "AX-MEM-DDR5-7200-16G",
      imageUrl: "https://picsum.photos/seed/axiom-frost-ddr5-7200-16gb/800/600",
      badge: "On Sale",
      specs: [
        { name: "Capacity", value: "16GB (2x8GB)" },
        { name: "Type", value: "DDR5" },
        { name: "Speed", value: "7200 MT/s" },
        { name: "Latency", value: "CL34-44-44-96" },
        { name: "Voltage", value: "1.40V" },
        { name: "Profile", value: "XMP 3.0 / EXPO" },
        { name: "RGB", value: "None" },
        { name: "Form Factor", value: "DIMM" },
      ],
      variants: [],
      tags: ["ddr5", "ddr5-7200", "entry", "value"],
    },
    {
      name: "AXIOM BOLT SATA SSD 4TB",
      slug: "axiom-bolt-sata-ssd-4tb",
      category: "Storage",
      categorySlug: "storage",
      shortDescription: "4TB SATA SSD with 560 MB/s — bulk storage at SSD speeds",
      description: "Massive SATA SSD capacity for workstations, NAS, and media production. The BOLT uses 3D TLC NAND for a balance of endurance and cost-efficiency.",
      basePrice: "249.99",
      salePrice: null,
      stock: 35,
      sku: "AX-SSD-BOLT-4TB-SATA",
      imageUrl: "https://picsum.photos/seed/axiom-bolt-sata-ssd-4tb/800/600",
      badge: null,
      specs: [
        { name: "Capacity", value: "4TB" },
        { name: "Interface", value: "SATA 6Gb/s" },
        { name: "Form Factor", value: "2.5\" 7mm" },
        { name: "Sequential Read", value: "560 MB/s" },
        { name: "Sequential Write", value: "520 MB/s" },
        { name: "NAND Type", value: "3D TLC NAND" },
        { name: "Endurance", value: "2,400 TBW" },
        { name: "Warranty", value: "5 Years" },
      ],
      variants: [
        { id: 1, name: "2TB", sku: "AX-SSD-BOLT-2TB-SATA", priceModifier: -100, stock: 20, attributes: { capacity: "2TB" } },
        { id: 2, name: "4TB", sku: "AX-SSD-BOLT-4TB-SATA", priceModifier: 0, stock: 15, attributes: { capacity: "4TB" } },
      ],
      tags: ["ssd", "sata", "storage", "bulk"],
    },
    {
      name: "AXIOM PULSE PSU 850W Platinum",
      slug: "axiom-pulse-psu-850w-platinum",
      category: "Power Supplies",
      categorySlug: "psus",
      shortDescription: "850W 80+ Platinum semi-modular — balanced efficiency at a great price",
      description: "Premium reliability without premium pricing. The PULSE 850W Platinum is the ideal choice for mid-range to high-end gaming builds up to RTX 5080 / RX 9900 XTX.",
      basePrice: "139.99",
      salePrice: null,
      stock: 48,
      sku: "AX-PSU-PULSE-850P",
      imageUrl: "https://picsum.photos/seed/axiom-pulse-psu-850w-platinum/800/600",
      badge: null,
      specs: [
        { name: "Wattage", value: "850W" },
        { name: "Efficiency", value: "80+ Platinum (94% @ 50% load)" },
        { name: "Modular", value: "Semi-Modular" },
        { name: "Fan Size", value: "120mm" },
        { name: "ATX Version", value: "ATX 3.0" },
        { name: "PCIe Cables", value: "1x 16-pin 12VHPWR, 2x PCIe 8-pin" },
        { name: "Warranty", value: "7 Years" },
      ],
      variants: [],
      tags: ["psu", "platinum", "850w", "semi-modular"],
    },
    {
      name: "AXIOM CORE ULTRA 5 245K",
      slug: "axiom-core-ultra-5-245k",
      category: "Processors",
      categorySlug: "cpus",
      shortDescription: "14 cores (6P+8E) Arrow Lake — precision value for gamers",
      description: "The Core Ultra 5 245K delivers competitive gaming performance and strong content creation at an accessible price point on the Intel Z890 platform.",
      basePrice: "309.99",
      salePrice: "279.99",
      stock: 35,
      sku: "AX-CPU-CU5-245K",
      imageUrl: "https://picsum.photos/seed/axiom-core-ultra-5-245k/800/600",
      badge: "On Sale",
      specs: [
        { name: "Socket", value: "LGA1851" },
        { name: "Cores / Threads", value: "14C (6P+8E) / 14T" },
        { name: "Boost P-Core Clock", value: "5.2 GHz" },
        { name: "Total Cache", value: "24MB L3 + 26MB L2" },
        { name: "TDP", value: "125W PBP / 159W MTP" },
        { name: "Architecture", value: "Arrow Lake" },
        { name: "Memory Support", value: "DDR5-6400 (native)" },
      ],
      variants: [],
      tags: ["intel", "lga1851", "arrowlake", "value", "gaming"],
    },
  ]);

  console.log("✅ AxiomCraft database seeded successfully!");
  console.log("   - 6 categories");
  console.log("   - 20 products across all categories");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
