import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import cartRouter from "./cart";
import authRouter from "./auth";
import dealsRouter from "./deals";
import wishlistRouter from "./wishlist";
import adminRouter from "./admin";
import branchesRouter from "./branches";
import accessCodesRouter from "./access-codes";
import branchProductsRouter from "./branch-products";
import restockRouter from "./restock";
import userOrdersRouter from "./user-orders";
import storageRouter from "./storage";
import reservationsRouter from "./reservations";
import reviewVotesRouter from "./review-votes";
import orderTrackingRouter from "./order-tracking";
import localizationRouter from "./localization";
import checkoutRouter from "./checkout";
import webhookRouter from "./webhook";
import contactRouter from "./contact";
import customerBenefitsRouter from "./customer-benefits";
import searchSlangRouter from "./search-slang";
import compatibilityGamesRouter from "./compatibility-games";
import bundlesRouter from "./bundles";
import codEscrowRouter from "./cod-escrow";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(productsRouter);
router.use(cartRouter);
router.use(authRouter);
router.use(dealsRouter);
router.use(wishlistRouter);
router.use(adminRouter);
router.use(branchesRouter);
router.use(accessCodesRouter);
router.use(branchProductsRouter);
router.use(restockRouter);
router.use(userOrdersRouter);
router.use(reservationsRouter);
router.use(reviewVotesRouter);
router.use(orderTrackingRouter);
router.use(localizationRouter);
router.use(checkoutRouter);
router.use(webhookRouter);
router.use(contactRouter);
router.use(customerBenefitsRouter);
router.use(searchSlangRouter);
router.use(compatibilityGamesRouter);
router.use(bundlesRouter);
router.use(codEscrowRouter);

export default router;
